### ISSUE TITLE
Generate step defintion for new line

### ISSUE THREAD

**Issue by RobelCSUN** [alexkrechik/VSCucumberAutoComplete#305] opened 2019-11-20 21:35 UTC
**Describe the bug**
When writing new gherkin line, it does not give you an option to generate a step definition method. 

**To Reproduce**
1. Create new .feature file
2. Write a new gherkin line.
3. It shows warning saying that "Was unable to find step..." because it does not have step yet
4. When hover over the warning, it says "No quick fixes available". 

**Expected behavior**
I am expecting the tool to give you an option to auto generate the step definition just like using other IDEs such us IntelliJ .

**Screenshots**

"cucumberautocomplete.steps": 
        [
             "**/*.java"
        ],
    "cucumberautocomplete.syncfeatures": "**/*.feature"

**Comment by alexkrechik** [comment] 2019-11-25 16:56
Duplicate of https://github.com/alexkrechik/VSCucumberAutoComplete/issues/48. Not sure how to fix this issue to cover most potential cases, but will try to do some simple fix at the nearest release.

**Closed by alexkrechik** 2019-11-25 16:56 UTC
