### ISSUE TITLE
Not found until reopen

### ISSUE THREAD

**Issue by st-schneider** [alexkrechik/VSCucumberAutoComplete#296] opened 2019-09-19 06:58 UTC
Issue Type: <b>Bug</b>
Sometime when having feature and step definition side by side, the feature is unable to find the newly added step definition until I reopen the feature file.

Extension version: 2.14.1
VS Code version: Code - Insiders 1.39.0-insider (6a54c8176fd60745ad7f2ba9dc89af4631752bae, 2019-09-18T15:26:55.541Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.55GB free)|
|Process Argv|-psn_0_860370|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kimberley2310** [comment] 2021-03-19 09:30
Good morning,

Today we were having the same issue as you described here. We created a new file for step definitions (global step definitions) and added two steps. Both steps do not pop-up in the feature file as a suggestion and are also not recognized.
After closing the feature file and opening it again the steps were updated and recognized.

We made some screenshots so you can see how to reproduce the issue. We saw that Alex already tagged it with can't reproduce so hopefully we can help now to reproduce the issue.

Version: 2.15.1
Visual Studio Code version: 1.54.3

![p9og5](https://user-images.githubusercontent.com/80951448/111759478-ed745800-889d-11eb-8c58-90c86b441789.png)

**Closed** 2022-07-02 10:36 UTC
Labels: bug, can't reproduce
