### ISSUE TITLE
feature file failed to be formatted when scenario ends with .json

### ISSUE THREAD

**Issue by Hemanbaba** [alexkrechik/VSCucumberAutoComplete#290] opened 2019-08-05 06:42 UTC
If a scenario ends with .json, the rest will be failed to be formatted

Reproduce Step:
Copy below scripts into a .feature file in VScode. we can see the second one are all in white without color. And try to comment out one line will start with // instead of #  

Scenario: Searches Case 1-1 xxx for  type = 55
  When a client makes a request to create search id for object type 55
  Then rest server returns a http status of 200
  And the JSON in response should match the searches base line Searches1-1.json

Scenario: Searches Case 1-1 xxx for  type = 55
  When a client makes a request to create search id for object type 55
// Then rest server returns a http status of 200
  And the JSON in response should match the searches base line Searches1-1.json

**Comment by alexkrechik** [comment] 2019-10-10 16:07
Was unable to reproduce this issue - please see at the screen. Is the issue still be valid for you? Could you please provide a screenshot of the issue, if valid?
![Screen Shot 2019-10-10 at 7 05 18 PM](https://user-images.githubusercontent.com/5772406/66586347-22508b80-eb91-11e9-8ac5-0028277f6cdd.png)

**Comment by Hemanbaba** [comment] 2019-10-31 08:01
> Was unable to reproduce this issue - please see at the screen. Is the issue still be valid for you? Could you please provide a screenshot of the issue, if valid?
> ![Screen Shot 2019-10-10 at 7 05 18 PM](https://user-images.githubusercontent.com/5772406/66586347-22508b80-eb91-11e9-8ac5-0028277f6cdd.png)

The screenshot is exactly the issue I mentioned, the second scenario is without color formatted, plus RMC and Format Document didn't work at all.
However, now it's no longer valid. I can see the scenario with color correctly formatted and RMC plus Format Document also works fine

**Comment by JamieBriersSageCom** [comment] 2020-04-03 12:53
This happens after the word 'json'.

I have a step 'I set accept header to application/json' and the same issue happens.

**Comment by Hemanbaba** [comment] 2020-04-17 03:03
The issue has been occurring again in this year.

**Comment by alexkrechik** [comment] 2020-11-15 10:26
Fixed in 2.15.1

**Closed by alexkrechik** 2020-11-15 10:26 UTC
Labels: bug

**Comment by JDUNNIN** [comment] 2021-04-08 08:59
Hi @alexkrechik - I have v2.15.1 installed which should resolve this issue but I still see it when a step ends with `JSON`.  Adding text after `JSON` resolves the issue.
e.g.
```
Feature: mapping tests

    @Employee
    Scenario Outline: a mock scenario
        Given a yml response mapping "<ins1>"
        And a response JSON "<ins2>"
        When I apply the yml response mapping to the response JSON <-- syntax highlighting breaks from here.
        Then the mapping output matches the expected output "<ins3>"

    Examples:
    | ins1 | ins2 | ins3 |
    | Employee_01.yml  | Employees.json  | Employee_01.json  |
    | Employee_02.yml  | Employees.json  | Employee_02.json  |
```
VSCode version:
```
Version: 1.55.0
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:05.981Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
```

Thanks

**Comment by nprav** [comment] 2024-10-18 06:01
@alexkrechik I see this same issue occurring again.
Ie. gherkin syntax highlight stops working after a 'json' is detected in a line.

![image](https://github.com/user-attachments/assets/949eb208-cff7-44a1-bed4-3f443cfd7c1a)

![image](https://github.com/user-attachments/assets/f12a4afb-5a58-4a81-836e-867e16c52f21)


Note the difference in highlighting for the And, Then, But gherkin keywords.

I am using extension v3.0.5
Vscode version: 1.94.2

I see this commit was done to fix this previously: https://github.com/alexkrechik/VSCucumberAutoComplete/pull/348/commits/781aad35d3609012b37d7a7db6e61738b43af2dd

But the file no longer exists in the repo, and a similar file does not have the same changes: https://github.com/alexkrechik/VSCucumberAutoComplete/blob/master/syntaxes/json-embed.json#L8

Can this be fixed again?

By the way, this is an awesome extension. Really appreciate the work done.
