### ISSUE TITLE
Finding step definitions

### ISSUE THREAD

**Issue by akapitoha** [alexkrechik/VSCucumberAutoComplete#79] opened 2017-05-21 21:13 UTC
Hi Alex,
it's maybe not an issue, but a question: should I specify all my steps files in settings.json so I can find step definition from a feature file? Is there any way to do that with a file mask? I tried
"features/step_definitions/*.rb", -> that didn't work.
"features/step_definitions/**/*.rb" -> that finds completely wrong definitons (even from wrong files)
thank you

**Comment by alexkrechik** [comment] 2017-05-22 07:53
Hi!
You should use glob wildcard to find your steps (looks like "features/step_definitions/*.rb" in your case). Anyway, you can test your pathes using http://www.globtester.com/ for ex.

**Comment by akapitoha** [comment] 2017-05-22 08:28
Hi,
it was my typo, I used as you recommended "features/step_definitions/*.rb" (also tested it on http://www.globtester.com/), but for any step it always opens the same definition from a wrong file.

**Comment by alexkrechik** [comment] 2017-05-22 09:05
Got it. Could you please provide the step line, where all the definitions are redirecting to ?

**Comment by akapitoha** [comment] 2017-05-22 09:15
For example: I have X.feature, X_steps.rb.
step: `And go Next` (and others)
redirecting to Y_steps.rb:
`Then(/^I do Fast Sign in with "([^"]*)" and "([^"]*)"$/)do |email, pwd|`

my folder structure:
- test
--.vscode
--features
---step_definitions

**Comment by alexkrechik** [comment] 2017-05-22 15:45
I've reproduced this. Looks like an application issue. I'll Fix this in the nearest scope.

**Comment by alexkrechik** [comment] 2017-05-26 17:03
Should be fixed in 2.2.0

**Closed by alexkrechik** 2017-05-26 17:03 UTC

**Comment by akapitoha** [comment] 2017-05-26 18:47
Thanks a lot Alex! Looks fine now.
Thanks for your extension!
