### ISSUE TITLE
Step def with ruby interpolation aren't detect

### ISSUE THREAD

**Issue by alessandro-terenghi** [alexkrechik/VSCucumberAutoComplete#65] opened 2017-04-21 09:46 UTC
Step doesn't match if regular expression, in a step definition, contains a ruby interpolation as follow for example:

`Then(^the (#{SOMETHING}) cannot  work$)`

I did a fix replacing this [line](https://github.com/alexkrechik/VSCucumberAutoComplete/blob/master/gserver/src/steps.handler.ts#L76) with this one:
`let stepText = match[4].replace(/#{(.*?)}/g, '.*');`

hope this sounds good

**Comment by alexkrechik** [comment] 2017-04-24 08:50
The problem is more global. In the current extension implementation we can't interpolate 'Then(^the (#{SOMETHING}) cannot work$)' string as page object string due to no 'regexp' symbols between brackets (actually, ' " and / looks good - Then('^the (#{SOMETHING}) cannot work$') will be fine for ex.). So, some steps detection rework is required.

**Comment by alessandro-terenghi** [comment] 2017-04-26 07:18
What I wrote it was pseudo-code, so it wasn't a really regexp, ruby+cucumber is colser to js than java.
 I'm reporting a valid stepdef with intepolation in ruby as you can below.

`Then(/^the (#{SOMETHING}) cannot work$)`

where SOMETHING is could be something like 
```
SOMETHING = Transform(/^something'([^']*)'$/) do |filepath|
  do something;
end  
```

Interpolation, as you can see, can be very useful when we want to reuse some part of regexp in others steps def.

Hope this can clarify your doubts and exaplain the purpose of my proposal implementation.

**Comment by alessandro-terenghi** [comment] 2017-04-26 12:57
If you're agree I can push my work on a branch so you can review it (currently I haven't enough grants)

**Comment by alexkrechik** [comment] 2017-04-26 14:37
There are some other step text replacements [here](https://github.com/alexkrechik/VSCucumberAutoComplete/blob/master/gserver/src/steps.handler.ts#L82). So, I believe, that some separate method should be created for such purposes. You can push your changes via pull request (please consider, that tests should be updated and passed in this case) and I will refactor them later, or I can do refactoring with your changes implementation.

**Comment by alexkrechik** [comment] 2017-04-27 16:51
Thank you for your issue and pull request. I've merged it with some changes from my side and will publish it with the nearest extension release (I've to complete several more issues fixing).

**Comment by alessandro-terenghi** [comment] 2017-04-28 07:08
Glad to help you.

**Comment by alexkrechik** [comment] 2017-05-26 17:06
Realized in 2.2.0

**Closed by alexkrechik** 2017-05-26 17:06 UTC
