### ISSUE TITLE
Unable to recognize steps with empty string parameter

### ISSUE THREAD

**Issue by badeball** [alexkrechik/VSCucumberAutoComplete#294] opened 2019-09-03 07:18 UTC
**Describe the bug**
Steps with empty string parameters doesn't get recognized and the file gets underlined as faulty.

**Expected behavior**
I expect it to correctly map a step to a step definition.

**Cucumberautocomplete part of VSCode settings:**
```
{
	"cucumberautocomplete.steps": [
		"test/e2e/cypress/integration/step_definitions/*.js"
	],
	"cucumberautocomplete.syncfeatures": "test/e2e/cypress/integration/**/*.feature",
	"cucumberautocomplete.strictGherkinCompletion": true
}
```

**Step definition:**
```
Then("I should see a field {string} with {string}", (label, text) => {
  // ...
});
```

**Gherkin step line**
```
Then I should see a field "foo" with ""
```

**Comment by reynoldsbj** [comment] 2019-11-15 18:12
To add to this, I've also seen the below scenario:

**Step definition:**
`
Then("I should see a field {string} with {string}", (label, text) => {
  // ...
});

Then("I should see a field {string}", (label) => {
  // ...
});
`

**Gherkin step line:**
`
Then I should see a field "foo" with ""
`
**Expected Behavior:**
Above step matches to first step definition
**Actual Behavior:**
Above step matches to second step definition

**Comment by Roaders** [comment] 2019-12-16 14:13
upvote from me please.

**Comment by asze** [comment] 2020-02-24 19:50
Per the [Cucumber documentation](https://cucumber.io/docs/cucumber/cucumber-expressions/#parameter-types) on `{string}`...
> Empty pairs of quotes are valid and will be matched and passed to step code as empty strings.

If I had to guess, the problem is at least in part caused by this incorrect regular expression:
https://github.com/alexkrechik/VSCucumberAutoComplete/blob/master/gserver/src/steps.handler.ts#L209-L210
`'"[^"]+"'` is what this plugin is looking for, but the Cucumber documentation suggests that it should instead be `'"[^"]*"'`.

**Comment by hdhaussy** [comment] 2021-09-23 13:24
Facing the same problem, I put this in VSCode settings as a workaround :
```
{
    "cucumberautocomplete.customParameters": [
        {
            "parameter":"{string}",
            "value":"\"[^\"]*\""
        },
    ],
} 

```

**Comment by alexkrechik** [comment] 2022-07-04 13:58
Should be fixed now

**Closed by alexkrechik** 2022-07-04 13:58 UTC
Labels: bug, priority
