### ISSUE TITLE
Unable to find step - language issue

### ISSUE THREAD

**Issue by MichalFidor** [alexkrechik/VSCucumberAutoComplete#236] opened 2019-01-08 07:40 UTC
**Describe the bug**
In the latest version, you added an "I" as a step ("and") to the interpreter. I think, that there should be some option to set a default language to this extension or to somehow ignore the description area (it will be more difficult I think). Because in Polish there is an "I" and it means in fact "and" but if I use English in my project, and I would like to use "I" as I/Me into the description then it shouldn't underline this as a step.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to VSC with the extension installed 
2. Create new .feature file
3. Fill it up with e.g. 
```
Feature: <title>
  
    As an (..)
    I want a (...)

        Scenario: <scenario title>
        Given <some existing step>
```

4. After that, you can see that "I want a (...)" will be underlined

**Expected behaviour**
It shouldn't underline this as a step, because this is just a description

**Screenshots**
![issue](https://user-images.githubusercontent.com/42964298/50816282-5821c480-1320-11e9-80ba-66e5bf7980ab.png)

**Comment by rayk47** [comment] 2019-02-14 20:02
Yes pls this one is very frustrating

**Comment by DesHorsley** [comment] 2019-02-16 11:51
Is this a duplicate of #234 ?

**Comment by MichalFidor** [comment] 2019-02-18 11:07
Yes, it's the same issue. Didn't noticed that someone already created a topic for that. 
Alex replied on the [marketplace](https://marketplace.visualstudio.com/items?itemName=alexkrechik.cucumberautocomplete#qna) that I should create a new card for that and I just did it without looking if there is a related topic created already.

**Comment by alexkrechik** [comment] 2019-02-24 15:50
Hotfixed in 2.13.1

**Comment by rayk47** [comment] 2019-02-25 18:39
Confirmed this is working thanks @alexkrechik

**Closed** 2019-02-26 08:38 UTC
