### ISSUE TITLE
CucumberAutocomplete syntax

### ISSUE THREAD

**Issue by NyanHorse** [alexkrechik/VSCucumberAutoComplete#282] opened 2019-07-09 16:31 UTC
When I write a test this way is ok:

* Given('I open the login page', () => {
     cy.visit('/')
  })
* `Given(“I open the login page”, () => { cy.visit('/') })`
* `Given(`\`I open the login page\``, () => { cy.visit('/') })`

But if I use single quotes this way:

* `Given('I open the login page', () => { cy.visit('/') })`

it throws this error in the .feature file -> Was unable to find step for “Given I open the login page”

<img width="500" alt="Screenshot 2019-07-09 at 18 30 52" src="https://user-images.githubusercontent.com/36642164/60906581-bb60c500-a277-11e9-9e01-26596fe8c519.png">

Why is this happening?

**Comment by alexkrechik** [comment] 2019-09-17 16:28
The issue is related to single quotes at the end of string.

**Comment by alexkrechik** [comment] 2022-07-03 13:10
Should already be fixed in another ticket scope

**Closed by alexkrechik** 2022-07-03 13:10 UTC
Labels: bug
