### ISSUE TITLE
How to generate step definition from feature file

### ISSUE THREAD

**Issue by Dipak2381** [alexkrechik/VSCucumberAutoComplete#257] opened 2019-04-03 08:35 UTC
![image](https://user-images.githubusercontent.com/26186329/55464779-c01c3a00-55f3-11e9-8ca7-eb1edb0d8207.png)

**Comment by alexkrechik** [comment] 2019-04-14 14:05
Closed as duplicate of https://github.com/alexkrechik/VSCucumberAutoComplete/issues/48

**Closed by alexkrechik** 2019-04-14 14:05 UTC
